[platformio]
default_envs = AT17C65_Programmer

[env:AT17C65_Programmer]

platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board = rpipico2
board_build.core = earlephilhower
;lib_deps =
build_flags =
    -O2 -Isrc
    -Wall -Wno-sign-compare -Wno-ignored-qualifiers
    -D PICO_CYW43_ARCH_NONE
